CRUD company #8
zinza-d2-training/hungnv-php pull request #18
Opened 2022-06-07 04:32 UTC by hungnv1zinza

2022-06-07 04:55 UTC, cuongnxzinza commented on app/Http/Controllers/CompanyController.php
> +    public UploadFileServiceInterface $uploadFileService;
sử dụng private thay vì public các biến này nhé e

2022-06-07 05:02 UTC, cuongnxzinza requested changes

2022-06-07 05:02 UTC, cuongnxzinza commented on app/Http/Controllers/CompanyController.php
> +    public UploadFileServiceInterface $uploadFileService;
sử dụng private cho các property

2022-06-07 05:02 UTC, cuongnxzinza commented on app/Http/Controllers/CompanyController.php
> +        $company = new Company();
ko cần phải khởi tạo như thế này. Có thể sử dụng trực tiếp Company::create($data)

2022-06-07 05:02 UTC, cuongnxzinza commented on app/Http/Controllers/CompanyController.php
> +        $data['status'] = $request->input('status');
$data = $request->validated() đã validate rồi trả về dữ liệu tin tưởng r mà. E dùng $request->input để lấy làm gì. Bản thân $data đã chứa address với status rồi mà?

2022-06-07 05:02 UTC, cuongnxzinza commented on app/Http/Controllers/CompanyController.php
> +    public function show($id)
xóa những phần không sử dụng

2022-06-07 05:02 UTC, cuongnxzinza commented on app/Http/Controllers/CompanyController.php
> +        return redirect()->route('companies.index')->with(['status' => 'success', 'message' => "Cập nhật dữ liệu thành công"]);
xử lý tương tự comment trên

2022-06-07 05:02 UTC, cuongnxzinza commented on app/Observers/CompanyObserver.php
> +    }
xóa code thừa

2022-06-07 05:02 UTC, cuongnxzinza commented on app/Http/Controllers/UserController.php
> +        $filename = $this->uploadFileService->uploadFile($data['avatar'], 'user');
không nên sử dụng magic string hoặc magic number

2022-06-07 05:02 UTC, cuongnxzinza commented on app/Services/UploadFileService.php
> +            'uploads/'.$path.'/',
chú ý format lại code

2022-06-07 05:02 UTC, cuongnxzinza commented on resources/views/company/edit.blade.php
> +                                <option value="1" {{ $company->status == 1 ? 'selected' : '' }}>Active</option>
hạn chế dùng magic number

2022-06-07 05:02 UTC, cuongnxzinza commented on resources/views/company/edit.blade.php
> +            input.addEventListener('change', (e) => {
phần này có thể tạo lib để xử lý riêng được không?

2022-06-07 05:02 UTC, cuongnxzinza commented on routes/web.php
> +    Route::resource('companies', CompanyController::class);
nếu k sử dụng full các route thì dùng except hoặc only để chỉ định những route sử dụng

2022-06-07 07:14 UTC, hungnv1zinza commented on app/Http/Controllers/CompanyController.php
> +        $data['status'] = $request->input('status');
Những trường kia nó k nằm trong $data anh ạ

2022-06-08 02:23 UTC, phuongcm-zinza requested changes

2022-06-08 02:23 UTC, phuongcm-zinza commented on app/Http/Controllers/UserController.php
> +        }
có thể xem xét cho đoạn hash pass này vào observer nhé

2022-06-08 02:23 UTC, phuongcm-zinza commented on app/Http/Requests/Company/CompanyRequest.php
> +            'expired_at' => 'required',
Rule validate phải kèm kiểu dữ liệu nếu là dữ liệu đặc thù, nhưng tốt nhất là tất cả đều thêm kiểu dữ liệu vào VD: 'name' => 'required|string|max:100',

2022-06-08 02:23 UTC, phuongcm-zinza commented on app/Http/Controllers/CompanyController.php
> +        $data['expired_at'] = Carbon::createFromFormat('d/m/Y', $data['expired_at'])->format('Y-m-d');
Cái expired_at a thấy có observer cho create rồi, chú apply luôn cho update nhé

2022-06-08 02:23 UTC, phuongcm-zinza commented on resources/views/layouts/app.blade.php
> +            @endif
format lại đoạn này nhé

2022-06-08 02:23 UTC, phuongcm-zinza commented on resources/views/user/setting.blade.php
> +        <script src="/js/datepicker.js"></script>
nên sử dụng hàm asset để nhập link js css

2022-06-08 03:07 UTC, merged